# Default values for span-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# run every 5 minutes
schedule: "30 */6 * * *"

successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 10

janitor:
  image: hjacobs/kube-janitor:0.7
  env: []
  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 5m
      memory: 100Mi

rules: {}

serviceAccount: ""

nodeSelector: {}

tolerations: []

affinity: {}

labels:
  configMap: {}
  cronJob: {}
  pods: {}

annotations:
  configMap: {}
  cronJob: {}
  pods: {}
