apiVersion: v1
appVersion: 20.4.1
description: Cleans up Kubernetes resources on a configured TTL
name: kube-janitor
version: 1.0.4
home: https://github.com/basisai/kube-janitor-helm
sources:
  - https://github.com/hjacobs/kube-janitor
  - https://github.com/basisai/kube-janitor-helm
